99cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    post 'approve', on: :member
    post 'deny', on: :member
  end

  root to: redirect('/cats')

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
end

99cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer          not null
#

require 'action_view'

class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper

  # freeze ensures that constants are immutable
  CAT_COLORS = %w(Black White Orange Brown).freeze

  validates :birth_date, :color, :name, :sex, :owner, presence: true
  validates :color, inclusion: CAT_COLORS
  validates :sex, inclusion: %w(M F)

  has_many :rental_requests,
    class_name: :CatRentalRequest,
    dependent: :destroy

  belongs_to :owner,
    foreign_key: :user_id,
    class_name: "User"

  def age
    time_ago_in_words(birth_date)
  end
end

99cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  before_action :ensure_owner, only: [:edit, :update]

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.owner = current_user
    if @cat.save
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :edit
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:age, :birth_date, :color, :description, :name, :sex)
  end

end

99cats/app/helpers/cats_helper.rb
module CatsHelper
end

99cats/app/views/cats/_form.html.erb
<% action = (cat.persisted? ? cat_url(cat) : cats_url) %>
<% method = (cat.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
  <input type = "hidden" value = '<%= form_authenticity_token %>' name = 'authenticity_token'/>
  <input type="hidden" name="_method" value="<%= method %>">

  <label for="cat_name">Name</label>
  <input
    type="text"
    name="cat[name]"
    id="cat_name"
    value="<%= cat.name %>">

  <label for="cat_birth_date">Birth date</label>
  <input
    type="date"
    name="cat[birth_date]"
    id="cat_birth_date"
    value="<%= cat.birth_date %>">
  <br>

  <label for="cat_color">Color</label>
  <select name="cat[color]" id="cat_color">
    <option></option>
    <% Cat::CAT_COLORS.each do |color| %>
      <option
        <%= cat.color == color ? "selected" : "" %>
        value="<%= color %>">
        <%= color.upcase %>
      </option>
    <% end %>
  </select>
  <br>

  <input
    type="radio"
    name="cat[sex]"
    value="M"
    id="cat_sex_male"
    <%= cat.sex == "M" ? "checked" : "" %>>
  <label for="cat_sex_male">Male</label>
  <input
    type="radio"
    name="cat[sex]"
    value="F"
    id="cat_sex_female"
    <%= cat.sex == "F" ? "checked" : "" %>>
  <label for="cat_sex_female">Female</label>
  <br>

  <label>
    Description
    <textarea name="cat[description]"><%= cat.description %></textarea>
  </label>

  <% submit_text = (cat.persisted? ? 'Update' : 'Create') + ' cat!' %>
  <input type="submit" value="<%= submit_text %>">
</form>

99cats/app/views/cats/_req_tr.html.erb
<tr>
  <td><%= req.start_date %></td>
  <td><%= req.end_date %></td>
  <td><%= req.requester.username %></td>
  <td>
    <% if req.pending? && is_owner? %>
      <form action="<%= approve_cat_rental_request_url(req) %>" method="POST">
        <input type = "hidden" value = '<%= form_authenticity_token %>' name = 'authenticity_token'/>
        <input type="submit" value="Approve" />
      </form>
      <form action="<%= deny_cat_rental_request_url(req) %>" method="POST">
        <input type = "hidden" value = '<%= form_authenticity_token %>' name = 'authenticity_token'/>
        <input type="submit" value="Deny" />
      </form>
    <% else %>
      <%= req.status %>
    <% end %>
  </td>
</tr>

99cats/app/views/cats/edit.html.erb
<h1>Edit My Cat</h1>
<%= render 'shared/errors' %>
<%= render 'form', cat: @cat %>

99cats/app/views/cats/index.html.erb
<h2 class = 'index-header'>Choose Your Cat!</h2>

<ul class = 'cat-list-ul'>
  <% @cats.each do |cat| %>
    <% random_cat = [1,2,3,4].sample %>
    <li class='one-third'><a class = 'cat-list' href="<%= cat_url(cat) %>"><img src="/assets/cat<%= random_cat %>.jpeg" alt="CATS"><br>
      <%= cat.name %></a></li>

  <% end %>
</ul>

<a href="<%= new_cat_url %>">Create cat</a>

99cats/app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'shared/errors' %>
<%= render 'form', cat: @cat %>

99cats/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<table>
  <tr>
    <th>Attribute</th>
    <th>Value</th>
  </tr>
  <% [:age, :birth_date, :color, :sex].each do |attr_name| %>
    <tr>
      <td><%= attr_name %></td>
      <td><%= @cat.send(attr_name) %></td>
    </tr>
  <% end %>
  <tr>
    <td> owner </td>
    <td><%= @cat.owner.username %> </td>
  </tr>
</table>

<%= link_to "Edit #{@cat.name}", edit_cat_url(@cat) %>

<h2>Rental Requests</h2>
<table>
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Requester</th>
    <th>Status</th>
  </tr>

  <% @cat.rental_requests.includes(:requester).order('start_date').each do |req| %>
    <%= render 'req_tr', req: req %>
  <% end %>

</table>