99cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    post 'approve', on: :member
    post 'deny', on: :member
  end

  root to: redirect('/cats')

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
end

99cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Libre+Barcode+39+Text" rel="stylesheet">
  </head>

  <body>

    <header>
      <h1>Rent-A-Cat</h1>


    <% if flash[:errors] %>
      <ul><%  flash[:errors].each do |error|  %>
        <li><%= error %></li>
        <% end %>
      </ul>
    <% end %>

    <% if logged_in? %>
      <%= button_to 'Logout', session_url, method: :delete, class: 'logout-button' %>
      <h4>Greetings, <%= current_user.username %> </h4>
    <% else %>
      <%= button_to 'Login', new_session_url, method: :get, class: 'logout-button' %>
      <%= button_to 'Register', new_user_url, method: :get, class: 'logout-button' %>
    <% end %>
    </header>
    <%= yield %>

  </body>
  <footer>
    <%= link_to 'Back to Index', cats_url %>
    <%= link_to 'New Rental Request', new_cat_rental_request_url %>
  </footer>
</html>